name: Release Workflow

on:
  push:
    tags:
      - 'r*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y nasm libgl-dev mingw-w64

      - name: Build Linux-x64
        run: OS=linux-x64 ./release.sh

      - name: Build Windows
        run: OS=windows-x64 ./release.sh

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          working_directory: dist
          files: '*'
